# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BonnieDraw' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BonnieDraw
  pod 'KYDrawerController'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'FacebookLogin'
  pod 'TwitterKit'
  pod 'Google/SignIn'
  pod 'DeviceKit'
  pod 'Alamofire'
  pod 'XLPagerTabStrip'
  pod 'DropDown'
end
