# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BonnieDraw' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BonnieDraw
  pod 'Fabric', '~> 1.7.2'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/Messaging'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'KYDrawerController'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'FacebookLogin'
  pod 'TwitterKit'
  pod 'Google/SignIn'
  pod 'DeviceKit'
  pod 'Alamofire'
  pod 'DropDown'
end
