# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
project 'BonnieDraw.xcodeproj'
target 'BonnieDraw' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BonnieDraw
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'KYDrawerController'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'FacebookLogin'
  pod 'TwitterKit'
  pod 'GoogleSignIn'
  pod 'DeviceKit'
  pod 'Alamofire'
  pod 'DropDown'
  pod 'XLPagerTabStrip'
end
